export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_FULL: "ROOM_FULL",
  GAME_ALREADY_STARTED: "GAME_ALREADY_STARTED",
  NOT_HOST: "NOT_HOST",
  NOT_YOUR_TURN: "NOT_YOUR_TURN",
  INVALID_ACTION: "INVALID_ACTION",
  ILLEGAL_ACTION: "ILLEGAL_ACTION",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  PLAYER_NOT_IN_ROOM: "PLAYER_NOT_IN_ROOM",
  ROOM_PAUSED: "ROOM_PAUSED",
  DUPLICATE_ACTION: "DUPLICATE_ACTION",
  RATE_LIMITED: "RATE_LIMITED",
  USERNAME_TAKEN: "USERNAME_TAKEN",
  ADMIN_ONLY: "ADMIN_ONLY"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface AppErrorPayload {
  code: ErrorCode;
  message: string;
  details?: unknown;
}
